<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>SFD.FileModifier.Core</RootNamespace>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Format.fs" />
    <Compile Include="SfdBinary.fs" />
    <Compile Include="WorldProperties.fs" />
    <Compile Include="Header.fs" />
    <Compile Include="Document.fs" />
    <Compile Include="Map.fs" />
    <Compile Include="Script.fs" />
  </ItemGroup>

</Project>
